from portfolio_optimizer.stock_choice.EMAChoice import EMAChoice
from portfolio_optimizer.stock_choice.MLChoice import MLChoice
from portfolio_optimizer.stock_choice.NaiveChoice import NaiveChoice
from portfolio_optimizer.stock_choice.SMAChoice import SMAChoice